me: Tony Scelfo
name: github.tonyscelfo.com
description: tales of a software ninjaneer
github_url: https://github.com/scelfo
g+_url: https://plus.google.com/110371866564374610674

paginate: 10
#markdown: maruku
permalink: date
pygments: true
