application: tony-scelfo
version: 3
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: _pagespeed/index.html
  upload: _pagespeed/index.html
- url: /[^\.]* # anything without a .
  script: _app.redirect.wsgi
- url: /(.+)
  static_files: _pagespeed/\1
  upload: _pagespeed/(.+)
