application: tony-scelfo
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: _pagespeed/index.html
  upload: _pagespeed/index.html
- url: /(.+)
  static_files: _pagespeed/\1
  upload: _pagespeed/(.+)
